Ugly
====

Traveling from Holland where every square meter is used for one purpose or another to East Germany where buildings fallen into disrepair and in various states of being reconquered by nature are a common sight I got a realization: There is value in ugliness and a spotless envirnoment is always creepy.

A beautiful spotless environment tells a story of strength, of surplus. It says here we have, here we can do, here we bend the world to our will. It exites.
But in the quitest of all voices you can hear the ghosts of all the ugly, the broken, the ill-fitting lament "this place has no mercy. This place killed us without ruth. This place is a battlefield, the ground soaked with our rubble."
And in the depth of our heart we wonder "Am not I sometimes ugly? Am not I sometimes broken? Am not I sometimes ill-fitting? Will this place show _me_ mercy if it has not shown it to the ugly?"

When I see a building, the windows broken, the roof caved in, a tree breaking up its foundation, I think of the cold, of dampness, of dirt and dust all to eager to settle into my clothes. I don't feel invited. My view turning inwards, recoiling from what this place is instead imagining what it could be.
But deep down I know if this can survive here so can I. If this can survive here so can my half-baked ideas. If this can survive here then this is a kind place.


