Urschleim the all birther
=========================

-second-page

-ugly

A human mind has to go beyond stories like a human leg has to go beyond pressing the gas pedal of a car.

Subsequent circles of circles of design, negotiation, navigating, hill climbing, wave climbing.
Consider hill-climbing, a (effectively) static environment in which agents do nothing else than go up slope. The immediate worry is that of local maxima. An agent climbing on the top of a hill and never moving towards a even higher hill top because in the immediate suroundings all directions are down slope.

The world is shaped by those for whom making decisions is a joyful activity.

Criticism of cis het white men gives the most emotionally mature cis het white men an opportunity for personal growth, perpetuating their privilege.

It is only through the adaptation of memory that a temporary short phenomenon like a thunder strike can have more impact on our thinking than a long lasting phenomenon like a rock.


Giving miners a choice of X $cryptocoin now vs. Y (Y > X) $cryptocoin later to scale mining reward with market cap. Not sure if possible but interesting idea.

Waves always travel towards the coast which is why the continets a constantly shrinking.

Central governments disallowing local gate keeping.

divide and conquer, blend and rule.
Governments being legitimized through the rule of law.

Whether a glass is half empty or half full depends on the distance to the next water tap.